spring.application.name=ProTraders
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/
server.error.include-binding-errors=never
server.error.include-message=never

spring.datasource.url=jdbc:mysql://localhost:3306/pro_traders
spring.datasource.username=root
spring.datasource.password=Protraders@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.main.web-application-type=servlet

spring.security.user.name=  
spring.security.user.password=

# Show generated SQL queries in the console
spring.jpa.show-sql=true

# Format the printed queries for better readability
spring.jpa.properties.hibernate.format_sql=true

spring.messages.basename=messages
spring.servlet.multipart.max-file-size=10MB

logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context=DEBUG

server.servlet.session.cookie.path=/
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=LAX
