pipeline:
  identifier: Build_ramsunnamuddi_ProTraders_1776594131067
  name: Build HarnessDemo
  orgIdentifier: default
  projectIdentifier: HarnessDemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1776594115383
        repoName: ramsunnamuddi/ProTraders
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: BUILD
                  identifier: BUILD
                  spec:
                    shell: Sh
                    command: |-
                      apt update
                      apt install openjdk-21-jdk -y
                      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
                      export PATH=$JAVA_HOME/bin:$PATH

                      java -version
                      mvn clean install

                      echo "=========installation completed========"

                      mvn test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
    - stage:
        name: snyk
        identifier: snyk
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: snyk_scan
                  identifier: snyk_scan
                  spec:
                    shell: Sh
                    command: |-
                      apt update

                      # install latest node (IMPORTANT)
                      apt install -y curl
                      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
                      apt install -y nodejs

                      # install snyk
                      npm install -g snyk

                      # DO NOT use snyk auth ❌
                      # just run test (token already in env)
                      snyk test --severity-threshold=high
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("snyk-token")>
  tags: {}
